import type { Metadata } from "next";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import "./globals.css";
import { AppThemeProvider } from "@/app/AppThemeProvider";
import { ThemeVars } from "@/app/ThemeVars";
import { AppProviders } from "./AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppThemeProvider>
          <ThemeVars />
          <AppProviders>
            <Header />
            {children}
            <Footer />
          </AppProviders>
        </AppThemeProvider>
      </body>
    </html>
  );
}
